### ISSUE TITLE
Module Name

### ISSUE THREAD

**Issue by waqaskanju** [ulisesedu7/AwesomeBooks-Modules#2]
Your overall codebase looks professional.
I would like to add some improvements.

- Kindly add names to your modules instead of Moudle1, Module 2

![image](https://user-images.githubusercontent.com/13853450/171198294-667c74ee-0890-49ec-ada1-6ab178b05f9f.png)

1. Also, add liners to your repo. There is only eslint available

![image](https://user-images.githubusercontent.com/13853450/171198626-a6e536e1-6105-4deb-9c62-4dafcd3e6235.png)
While all the linters are:
![image](https://user-images.githubusercontent.com/13853450/171198810-61097ea3-0573-4552-9715-df025280b396.png)

**Comment by ulisesedu7** [comment]
Thanks!!
